name: Build Executables

on:
  push:
    branches:
      - main  # ÂΩì‰ª£Á†ÅÊé®ÈÄÅÂà∞ main ÂàÜÊîØÊó∂Ëß¶Âèë
  workflow_dispatch:  # ÂÖÅËÆ∏ÊâãÂä®Ëß¶Âèë

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Current Version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Bump Version (Patch)
        run: |
          OLD_VERSION=$(cat version.txt)
          NEW_VERSION=$(echo $OLD_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo $NEW_VERSION > version.txt
          echo "New Version: $NEW_VERSION"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "üöÄ Bump version to $NEW_VERSION"
          git push origin main

      - name: Upload version file
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt


  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows Executable
        run: pyinstaller --onedir --windowed --distpath dist --upx-dir="C:\upx" --name wifi_scanner main.py || exit 1

      - name: Add License to Build
        run: cp LICENSE dist/LICENSE.txt  # Â§çÂà∂ GPL ËÆ∏ÂèØËØÅ


      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: wifi_scanner_windows
          path: dist/wifi_scanner.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Linux Executable
        run: pyinstaller --onefile --name wifi_scanner main.py

      - name: Add License to Build
        run: cp LICENSE dist/LICENSE.txt  # Â§çÂà∂ GPL ËÆ∏ÂèØËØÅ

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: wifi_scanner_linux
          path: dist/wifi_scanner
